--   Name: Thejus R
--   Reg no: CHN18CS118
--   Class: S5-C
--   Roll no: 59

CREATE TABLE SAILORS(
    SID INT PRIMARY KEY,
    SNAME CHAR(30),
    RATING FLOAT,
    AGE INT
);

INSERT INTO SAILORS VALUES ('301', 'TED', 3.9, 47);
INSERT INTO SAILORS VALUES ('302', 'BARNEY', 4.1, 29);
INSERT INTO SAILORS VALUES ('303', 'MARSHALL', 4.3, 32);

 CREATE TABLE BOATS(
     BID INT PRIMARY KEY,
     BNAME CHAR(30),
     COLOUR CHAR(10)
);
 
INSERT INTO BOATS VALUES ('101', 'SAVIOUR', 'RED'),
('102', 'SPIRIT', 'BLACK'),
('103', 'LIBERTY', 'BLUE');

CREATE TABLE RESERVES(
    SID INT,
    BID INT,
    DAY DATE
 );

INSERT INTO RESERVES VALUES ('303','101','2021-01-17'),
('301','102','2021-01-12'),
('303','103','2021-01-14'),
('301','103','2021-01-20');

#1
SELECT A.SID, A.SNAME, A.RATING, A.AGE
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID = C.SID AND C.BID = 101;

#2
SELECT B.BNAME
FROM RESERVES AS C
INNER JOIN SAILORS AS A ON A.SID = C.SID AND A.SNAME='MARSHALL'
INNER JOIN BOATS AS B ON B.BID = C.BID;

#3
SELECT A.SNAME
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID = C.SID
INNER JOIN BOATS AS B ON B.BID = C.BID AND B.COLOUR = 'RED'
ORDER BY A.AGE;

#4
SELECT DISTINCT A.SNAME
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID IN (C.SID);

#5
SELECT A.SID, A.SNAME
FROM RESERVES AS C
INNER JOIN RESERVES AS D ON C.SID <> D.SID AND C.DAY = D.DAY
INNER JOIN SAILORS AS A ON D.SID = A.SID;